OPENAI_API_KEY = "sk-yYNWmY5QhFAg57o3edkKT3BlGUweNuGV929"
OPENAI_MODEL = "gpt-4o-mini"

NEO4J_URI="neo4j+s://.databases.neo4j.io"
NEO4J_USERNAME="ne4j"
NEO4J_PASSWORD="B8NuxPgBcfEza3OSUijqhqfZAxZL8KgpwacJfZg"